---
language: node_js
node_js:
  - "6"
  - "5"
  - "4"

env:
  - PORT=5000

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install curl

script:
  # Start app
  - "npm start"

  # Check if app is lauched
  - "curl http://localhost"
